name: flutter_coffee_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  banner_carousel: ^1.2.1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  styled_divider: ^1.0.5
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.5
  flutter_dotenv: ^5.1.0
  icons_plus: ^5.0.0
  http: ^1.2.1
  ffi: ^2.0.1
  animated_text_kit: ^4.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  image_picker: ^1.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banner/
